review_detection/review_detection/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('review_detection_app.urls'))
]

review_detection/review_detection_app/urls.py
from django.urls import path
from . import views

urlpatterns = [
   path('', views.geturl),
]

review_detection/review_detection_app/models.py
from django.db import models

# Create your models here.

review_detection/review_detection_app/forms.py
from django import forms

class URLform(forms.Form):
    url = forms.URLField(max_length=250)

review_detection/review_detection_app/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from .forms import URLform
import pickle
import requests
import json
from bs4 import BeautifulSoup
import sklearn
import math
from amazon_product_review_scraper import amazon_product_review_scraper

from django.template import RequestContext

def geturl(request):
	if (request.method == "POST"):
		userform = URLform(request.POST)
		url = userform.data['url']

		try:
			product_code = getProductId(url)
			true, fake, adjustedRating,adjusted_star,star_t, star_f, mostHelpful = getReviews(product_code)

			star_t = list(star_t.values())
			star_t.reverse()
			star_f = list(star_f.values())
			star_f.reverse()

			productinfo = getProductInfo(url)
			productinfo['productid'] = product_code
			productinfo['url'] = url
			productinfo["reviews"] = true+fake

			context = {
				'product': productinfo,
				'true': true,
				'fake': fake,
				'adjusted': adjustedRating,
				'adjusted_star':adjusted_star,
				'star_t': star_t,
				'star_f': star_f,
				'mostHelpful': mostHelpful
			}

			return render(request, 'reviews.html', context)

		except Exception as e:
			print(e)
			return render(request, '404.html')

	else:
		form = URLform()
		return render(request , 'home.html', {'form': form})


def getviews(product_code):
	headers = {"User-Agent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:66.0) Gecko/20100101 Firefox/66.0", "Accept-Encoding":"gzip, deflate", "Accept":"text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8", "DNT":"1","Connection":"close", "Upgrade-Insecure-Requests":"1"}
	current_page = "https://www.amazon.in/product-reviews/" + product_code + "?pageNumber=1"
	response = requests.get(current_page, headers=headers)
	soup = BeautifulSoup(response.text, "html.parser")
	reviews = soup.find_all('div', class_ = "a-section review aok-relative")

	votes = []

	for review in reviews:
		try:
			cnt_helpful = review.find('span', class_ = 'cr-vote-text').text
			helpful_cnt = cnt_helpful[:cnt_helpful.index(' ')]

			if helpful_cnt == "One":
				helpful_votes = 1
			else:
				helpful_votes = int(cnt_helpful[:cnt_helpful.index(' ')])

		except:
			helpful_votes = 0

		votes.append(helpful_votes)

	return votes


def getProductInfo(url):
	# Set headers
	headers = {
		"User-Agent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:66.0) Gecko/20100101 Firefox/66.0",
		"Accept-Encoding":"gzip, deflate",
		"Accept":"text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8",
		"DNT":"1",
		"Connection":"close",
		"Upgrade-Insecure-Requests":"1"
	}

	# Connect to the URL
	response = requests.get(url, headers=headers)
	soup = BeautifulSoup(response.content, 'html.parser')

	if "not a robot" in soup.text:
		print("\n" + "-"*15 + "Captcha Required" + "-"*15 + "\n")

	# Parse HTML and save to BeautifulSoup object
	try:
		title = soup.find('span', id = 'productTitle').text.strip()
	except Exception as e:
		print(e)
		title = "Not Found"

	try:
		rating = soup.find('span', class_ = 'a-icon-alt').text.strip()
	except Exception as e:
		print(e)
		rating = "Not Found"

	try:
		reviews = soup.find('span', id = 'acrCustomerReviewText').text.strip()
	except Exception as e:
		print(e)
		reviews = "Not Found"

	try:
		image = soup.find('img', id = 'landingImage')['src'].strip()
	except Exception as e:
		print(e)
		image = "Not Found"

	try:
		price = soup.find('span', id = 'priceblock_ourprice').text.strip()
	except Exception as e:
		print(e)
		price = "Not Found"

	try:
		star_rating = float(rating.split(" ")[0])
		total_star = int(star_rating*100/5)
	except Exception as e:
		print(e)
		star_rating = 4.0
		total_star = 80

	return {
		"title": title,
		"rating": rating,
		"total_star":total_star,
		"star_rating":star_rating,
		"image": image,
		"price": price
	}

def getReviews(product_code):
	review_scraper = amazon_product_review_scraper(amazon_site="amazon.in", product_asin = product_code, end_page = 150)
	reviews_df = review_scraper.scrape()

	date = reviews_df['date_info'].tolist()
	name = reviews_df['name'].tolist()
	title = reviews_df['title'].tolist()
	Content = reviews_df['content'].tolist()
	Rating = reviews_df['rating'].tolist()

	pickle_in = open('models/review_detection.pickle', 'rb')
	pickle_clf = pickle.load(pickle_in)

	result = pickle_clf.predict(Content).tolist()
	true = result.count('1')
	fake = result.count('0')

	adj_rating = []
	votes = getviews(product_code)

	genuineReviews = [[votes[i], i] for i in range(len(votes)) if result[i] == '1']
	genuineReviews.sort(reverse = True)

	mostHelpfulReviews = []
	for i in range(min(3, len(genuineReviews))):
		ind = genuineReviews[i][1]
		mostHelpfulReviews.append(
			{
				"title": title[ind],
				"stars": int(Rating[ind].split('.')[0]),
				"content": Content[ind],
				"date": date[ind],
				"votes": genuineReviews[i][0]
			}
		)

	for i in range(len(Content)):
		if result[i]=='1':
			s1 = Rating[i].split('.')[0]
			adj_rating.append(int(s1))

	star_t = {1:0, 2:0, 3:0, 4:0, 5:0}
	star_f = {1:0, 2:0, 3:0, 4:0, 5:0}

	for i in range(len(Content)):
		s1 = int(Rating[i].split('.')[0])

		if(result[i]=='1'):
			star_t[s1] += 1

		elif(result[i]=='0'):
			star_f[s1] += 1

	result = round(sum(adj_rating)/true, 2)
	result_star= int(result*100 /5)
	return (true, fake, result, result_star,star_t, star_f, mostHelpfulReviews)

def getProductId(url):
	try:
		start = url.index('dp/') + 3
	except:
		start = url.index('product/') + 8

	end = url[start:].index('/') + start
	product_code = url[start:end]

	return product_code

review_detection/review_detection_app/templates/home.html
{% load static %}
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <title>Review Detection</title>

    <!-- Bootstrap Core CSS -->
    <link href="{% static 'bootstrap.min.css' %}" rel="stylesheet" type="text/css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">

    <link rel="stylesheet" href="css/bootstrap.min.css"/>
	<link rel="stylesheet" href="css/font-awesome.min.css"/>
	<link rel="stylesheet" href="css/flaticon.css"/>
	<link rel="stylesheet" href="css/owl.carousel.css"/>
	<link rel="stylesheet" href="css/magnific-popup.css"/>
	<link rel="stylesheet" href="css/style.css"/>

    <style type="text/css">

    	.topnav {
		  overflow: hidden;
		  background-color: #333;
		  width:100%;
		  position: fixed;
		}

		.topnav a {
		  float: left;
		  color: #f2f2f2;
		  text-align: center;
		  padding: 14px 16px;
		  text-decoration: none;
		  font-size: 17px;
		}

		.topnav a:hover {
		  background-color: #ddd;
		  color: black;
		}

		.topnav-right {
		  float: right;
		}

    	header {
    		text-align: center;
			background: #99ccff;
    		color: black;
    	}

    	header .container {
    		padding-top: 60px;
    		padding-bottom: 40px;
    		z-index: 1
    	}

    	header .intro-text {
    		display: block;
    		font-family: "Montserrat", "Helvetica Neue", Helvetica, Arial, sans-serif;
    		text-transform: uppercase;
    		font-weight: 700;
    		font-size: 2em;
    	}

    	@media (min-width: 768px) {
    		header .container { padding-top: 120px; padding-bottom: 70px; }
    		header .intro-text .name { font-size: 4.75em; }
    		header .intro-text .skills { font-size: 2em; }
    	}

    	.navbar-custom {
    		background: #2C3E50;
    		font-family: "Montserrat", "Helvetica Neue", Helvetica, Arial, sans-serif;
    		text-transform: none;
    		font-weight: 700;
			font-size: x-large;
    		border: none;
			padding-left: 5%;
			padding-right: 5%;
    		text-align: center;
    		color: white;
    		width: 100%;
    	}

    	hr{
    		border-top-color: black;
    	}

		#id_url {
			width: 70%;
			margin: 0 auto;
			color: black;
			font-weight: 100;
			font-size: medium;
		}

		.maincontent {
			display:block;
		}

		.loader {
			margin-top: 10%;
			display: none;
		}

		.loader img {
			height: 200px;
		}
		p{
			color: black;
		}

		.footer{
			background-color: black;
			align-content: center;
			color: white;
			height: 40px;
		}
		.footer p{
			text-align: center;
			color: white;
			font-size: 25px;
		}

		#sample1{
			height:30%;
			text-align: center;
			padding: 0px 150px 0px 150px;
		}
	
		#sample2{
			height: 350px;
			text-align: center;
			padding: 0px 150px 0px 150px;
		}

    </style>

</head>

<body class="index homepage">

	<div class="topnav">
	  <a href="#form">Review Detection</a>
	  <div class="topnav-right">
	    <a href="#about">About the App</a>
	    <a href="#contact">Contact Us</a>
	  </div>
	</div>


	<header>
		<div class="container" id="form">
			<div class="row maincontent">
				<div class="intro-text">
					<h1> Not sure Product reviews are Fake or Real? </h1>
					<h2> Check here &#8595;</h2>
					<hr class="star-light">
					<br/>
				</div>

				<form method="post" onsubmit="return showLoader();">

					{% csrf_token %}
					<div class="input-group" style="margin: 0 auto;">
						<label><h2>Enter URL</h2></label><br>
					</div>

					{{ form.url }}

					<br/><br/><br/>
					<input class="btn btn-primary" type="submit" value="Submit" style="font-size: 20px;">

				</form>
				<br><br><br><br><br><br><br>
				<br id="about"><br>
				<hr>
				<h2 ><b> About the App </b></h2>
				<hr>
				<h4 style="text-align: left"><p>People prefer to read reviews about a product before spending their money. If reviews are mostly positive, they tend to buy product.Significance of reviews is misused by parties who create fake reviews to increase popularity of their product or to defame product of competitors. Some good reviews are added by product company to produce fake positive review. Other companies defame product of competitors by giving fake negative reviews due to competition. Hence, people come across mixed reviews. This App is a system which detects fake reviews by using Classification Machine learning Model. </p>
				<br>

				<p>One of the reasons people love shopping on <b>Amazon</b> <i class="fa fa-amazon" style="font-size:24px;color:#00008B"></i> is that you can see all of the product ratings and reviews provided by other customers. In theory, these reviews and ratings help you know which products are good and which are bad. Unfortunately, many of the Amazon reviews cannot be trusted.</p>
				<br>

				<p><b>How to use this app?</b></p>
				<p><b style='font-size:30px;'>&#8688;</b> All you need to do is to copy the URL of Your product from Amazon and then paste on the search bar as shown in the picture below.</p>

				<p style="margin-top: 15px"><b style='font-size:30px;'>&#8688;</b> It will take some time to fetch the reviews from amazon and then the result will be provided.</p>
				<br>

				<p><b>What will be there in the result?</b></p>
				<p>The result will consist of:</p>
				<p><b style='font-size:30px;'>&#8688;</b> Adjusted Rating:</p>
				<p>Adjusted rating is the rating calculated after taking only the genuine ratings. It may be greater or smaller or equal than the actual rating depending on the defective reviews.</p>
				<br>
				<img src="{% static 'adjusted.PNG' %}" id="sample1"><img>

				<p style="margin-top: 15px"><b style='font-size:30px;'>&#8688;</b> Pie chart of Defective and True reviews:</p>
				<p>This Pie Chart is Used to represent the percentage of deceptive and genuine reviews of the product. The Red part of the chart consist total precentage of Deceptive reviews whereas the Green part consist total precentage of Genuine reviews.</p>
				<br>
				<img src="{% static 'pie.PNG' %}" id="sample2"><img>

				<p style="margin-top: 15px"><b style='font-size:30px;'>&#8688;</b>Double Bar Graph of Fake and true reviews as per Star rating:</p>
				<p>The double bar graph on the left scale consist of star rating from 1-5. The light blue bar is used to represent the count of Genuine reviews for the provided rating and dark blue bar is used to represent the count of Deceptive reviews for the provided rating.</p>
				<br>
				<img src="{% static 'bar.PNG' %}" id="sample2"><img>
				<br>

				<p style="margin-top: 15px"><b style='font-size:30px;'>&#8688;</b>Most Helpful Reviews</p>
				<p>This is used to show the top most three helpful reviews provided by customers.It will show the title of the review, content of the review, the star rating provided and the votes of people who find it helpful and the date of review. </p>
				<br>
				<img src="{% static 'Helpful.PNG' %}" id="sample2"><img>
				<br><br><br>
				<p style="color: #00008B;margin-top: 25px; font-size: 30px"><b>Note:</b> Make sure you use the URL from Amazon <i class="fa fa-amazon" style="font-size:24px;color:black"></i>.</p>
				</h4>

				<br><br><br><br><br><br><br>

				<hr id="contact">
				<h2><b> Contact Us</b></h2>
				<hr>
				<h3 style="text-align: center">
					<p>For any queries regarding the app Message us on the provided Email:</p>
					<p><span>&#9993;</span>bhalodiahr@rknec.edu</p>
                    <p><span>&#9993;</span>gajranibm@rknec.edu</p>
                    <p><span>&#9993;</span>agrawalkd_1@rknec.edu</p>
                    <br><br><br><br><br><br><br><br><br><br><br>
				</h3>

			</div>

			<div class="row loader" style="height:100%">
				<img src="{% static 'load.gif' %}"></img>
				<br><br>
				<h3><b>Your reviews are being processed...</b></h3>
				<h3><b>Please wait...</b></h3>
			</div>
		</div>
	</header>

	<div class="footer maincontent">
  		<p>Thank You for using this app. Hope it helped!</p>
	</div>
</body>

<script>
	function showLoader() {
		document.getElementsByClassName("maincontent")[0].style.display = "none";
		document.getElementsByClassName("maincontent")[1].style.display = "none";
		document.getElementsByClassName("loader")[0].style.display = "block";
	}
</script>

</html>

review_detection/review_detection_app/templates/reviews.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
	<title>Review database</title>
	<meta charset="utf-8">
	 <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
	<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>
	<script src="https://cdn.anychart.com/releases/8.9.0/js/anychart-core.min.js"></script>
	<script src="https://cdn.anychart.com/releases/8.9.0/js/anychart-pie.min.js"></script>
	<script src="https://cdn.anychart.com/releases/8.9.0/js/anychart-cartesian.min.js"></script>
</head>

<style type="text/css">

	.topnav {
		overflow: hidden;
		background-color: #333;
		width:100%;
	}

	.topnav a {
		 float: left;
		 color: #f2f2f2;
		 text-align: center;
		 padding: 14px 16px;
		 text-decoration: none;
		 font-size: 17px;
	}

	.topnav a:hover {
		background-color: #ddd;
		color: black;
	}

	.topnav-right {
		float: right;
	}

	#producturl:link, #producturl:visited {
		background-color: #f44336;
		color: white;
		padding: 14px 25px;
		text-align: center;
		text-decoration: none;
		display: inline-block;
	}

	#producturl:hover, #producturl:active {
		background-color: red;
	}

    #left {
    	text-align: center;
    	height:450px;
    }

    #right{
    	height: 450px;
    	text-align: center;
    }

    #adj {
		border: 2px solid black;
	 	width: 50%;
	  	background-color: #f0f5f5;
		text-align: center;
	}

    #stars {
    	width: 50%;
    }

	table, td {
		padding: 2%;
		border: 1px solid black;
		text-align: justify;
		vertical-align: top;
	}

	table {
		table-layout: fixed;
		width: 100%;
		border-top:3px solid black;
	}

	#helpfulReviews {
		background-color:ghostwhite;
		border: 3px solid black;
	}

	.rating{
		align-content:center;
		color: black;
	}

	#arrow{
		width: 80%;
		height: 40%;
	}

	.star_heading {
		font-size: 24px;
		font-weight: bold;
	}

	.final_rat{
		font-size: 50px;
		text-align: center;
	}

	.stars-container {
		position: relative;
		display: inline-block;
		text-align: center;
		font-size: 40px;
	}

	.stars-container:before {
		position: absolute;
		top: 0;
		left: 0;
		content: '★★★★★';
		color: lightgray;
	}

	.stars-container:after {
		position: absolute;
		top: 0;
		left: 0;
		content: '★★★★★';
		color: gold;
		overflow: hidden;
	}

	.stars-0:after { width: {{ product.total_star }}%; }
	.stars-1:after { width: {{adjusted_star}}%; }
</style>

<body>

	<div class="topnav maincontent">
	  <a href="/">Review Detection</a>
	</div>

	<div class="container" style="margin-top: 2%; margin-bottom: 2%;">
        <div class="row">
            <div class="col-lg-4">
                <img class="img-responsive" src="{{ product.image }}">
                <br><br>
                <a id="producturl" href="{{ product.url }}" target="_blank" style="">View the product on Amazon</a>
			</div>

			<div class="col-lg-8">
                <h2>{{ product.title }}</h2>
                <br>
                <h4><b>ASIN</b> - {{ product.productid }}</h4>
                <br>
                <h4><b>Price</b> - {{ product.price }}</h4>
                <br>
                <h4><b>Overall Rating</b> - {{ product.rating }} </h4>
                <br>
                <h4><b>Number of Reviews</b> - {{ product.reviews }} </h4>
            </div>
        </div>
	</div>

	<div class="container" id="adj">
		<div class="row" class="rating">
			<div style="margin-top: 6%; margin-bottom: 4%;" class="col-lg-4 col-md-4 col-sm-4" >
				<font class="star_heading">Amazon <i style="color:#FF9C33" class="fa"> &#xf270; </i> Rating</font>
				<br><br>
				<p class="final_rat"> {{ product.star_rating}} </p>
				<span class="stars-container stars-0">★★★★★</span>
			</div>

			<div class="col-lg-4 col-md-4 col-sm-4" style="margin-top: 7%; margin-bottom: 4%;">
				<img src="{% static 'arrow1.gif' %}" id="arrow"/>
			</div>

			<div style="margin-top: 6%; margin-bottom: 4%;" class="col-lg-4 col-md-4 col-sm-4" >
				<font class="star_heading">Adjusted Rating</font>
				<br><br>
				<p class="final_rat">{{ adjusted }}</p>
				<span class="stars-container stars-1">★★★★★</span>
			</div>
		</div>
	</div>

	<hr style="height:1px;border-width:0;color:gray;background-color:gray; width: 85%;">

	<div class="container" style="margin-top: 2%; margin-bottom: 5%;">
		<div class="row">
			<div id="left" class="col-lg-5">
				<h3>Genuine V/S Deceptive Reviews </h3>
			</div>
			<div id="right" class="col-lg-7">
				<h3>Rating wise distribution of Genuine and deceptive reviews</h3>
			</div>
		</div>
	</div>

	<hr style="height:1px;border-width:0;color:gray;background-color:gray; width: 85%;">

	<div class="container" style="margin-top: 2%; margin-bottom: 5%;" id="helpfulReviews">
		<div class="row">
			<div style="text-align: center; font-weight: 900;">
				<h1>Most Helpful Reviews</h1>
			</div>
		</div>

		<div class="row" style="margin-top: 1%;">
			<table>
				<tr>
					{% for helpful in mostHelpful %}
					<td>
						<h3 style="text-align: center;"> {{ helpful.title }} </h3>
						<br><br>
						{{ helpful.content }}
						<br><br>
						{% if helpful.stars == 1 %}
							<img src="../static/1star.png" id="stars">
						{% elif helpful.stars == 2 %}
							<img src="../static/2star.png" id="stars">
						{% elif helpful.stars == 3 %}
							<img src="../static/3star.png" id="stars">
						{% elif helpful.stars == 4 %}
							<img src="../static/4star.png" id="stars">
						{% else %}
							<img src="../static/5star.png" id="stars">
						{% endif %}
						<br><br>
						{{ helpful.votes }} Helpful Votes
						<br><br>
						{{ helpful.date }}
					</td>
					{% endfor %}
				</tr>
			</table>
		</div>
	</div>


</body>
<script>
	function drawPieChart() {
		var trueVal = "{{ true|safe }}";
		var fakeVal = "{{ fake|safe }}";

		// set the data
		var data = [
		{
			x: "Genuine",
			value: trueVal,
			normal:  {
				fill: "#1aff1a",
				hatchFill: "percent50"
			},
			hovered: {
				fill: "#1aff1a",
				hatchFill: "percent50",
				outline: {
					enabled: true,
					width: 6,
					fill: "#404040",
					stroke: null
				}
			},
			selected: {
				outline: {
					enabled: true,
					width: 6,
					fill: "#404040",
					stroke: null
				}
			}
		},
		{
			x: "Deceptive",
			value: fakeVal,
			normal:  {
				fill: "#e60000",
			},
			hovered: {
				fill: "#e60000",
				hatchFill: "percent50",
				outline: {
					enabled: true,
					width: 6,
					fill: "#404040",
					stroke: null
				}
			},
			selected: {
				outline: {
					enabled: true,
					width: 6,
					fill: "#404040",
					stroke: null
				}
			}
		}
		];

		// create the chart
		var chart = anychart.pie();

		// add the data
		chart.data(data);

		// display the chart in the container
		chart.container('left');
		chart.draw();
	}

	function drawBarGraph() {
		var star_t = JSON.parse("{{ star_t|safe }}");
		var star_f = JSON.parse("{{ star_f|safe }}");

		var data = anychart.data.set([
		  ["5★", star_t[0], star_f[0], {enabled: true}, ],
		  ["4★", star_t[1], star_f[1], {enabled: true}, ],
		  ["3★", star_t[2], star_f[2], {enabled: true}, ],
		  ["2★", star_t[3], star_f[3], {enabled: true}, ],
		  ["1★", star_t[4], star_f[4], {enabled: true}, ]
		]);

		// map the data
		var True = data.mapAs({x: 0, value: 1, label:3, });
		var Fake = data.mapAs({x: 0, value: 2, label:3, });

		// create a chart
		chart = anychart.bar();
		chart.labels().fontWeight(900);

		// create series and set the data
		var series1 = chart.bar(True);
		series1.name("Count of Genuine Reviews");

		var series2 = chart.bar(Fake);
		series2.name("Count of Deceptive Reviews");

		// enable legend
		var legend = chart.legend();
		legend.enabled(true);
		legend.position("bottom");
		legend.align("center");

		chart.container('right');
		chart.draw();
	}

	anychart.onDocumentReady(function() {
		drawBarGraph();
		drawPieChart();
	});

</script>
</html>